[build]
builder = "NIXPACKS"
buildCommand = "npm install --prefix backend"

[deploy]
startCommand = "npm start --prefix backend"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicy = "on-failure"
